### ISSUE TITLE
License

### ISSUE THREAD

**Issue by woody34** [anhr/ModifyRegistry#1]
Hello @anhr 

I am quickly throwing together a Desktop Support tool. I noticed you had no license. Would you mind if I used a portion of your code in my tool? I would give you an acknowledgment and link to your page. 

In full disclosure I already used some of your code before I realized you have no license setup but I will remove it if need be. Thanks!

**Comment by anhr** [comment]
Hello woody34, 

Yes. You can use my code.

Currently I am available. Do you or your friends have any work for me? Andrej


>Воскресенье, 18 ноября 2018, 9:41 +07:00 от woody34 <notifications@github.com>:
>
>Hello  @anhr
>I am quickly throwing together a Desktop Support tool. I noticed you had no license. Would you mind if I used a portion of your code in my tool? I would give you an acknowledgment and link to your page.
>In full disclosure I already used some of your code before I realized you have no license setup but I will remove it if need be. Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Andrej Hristoliubov

**Comment by woody34** [comment]
Thanks! Currently i have no work. I created a desktop support tool to improve my workflow at my job your project helped me to implement it quickly.
